language: node_js
node_js:
  - "node"
dist: trusty
addons:
  apt:
    packages:
      - texlive-xetex
      - ttf-dejavu
before_install:
  - npm install
  - node ./cli/wa2pdf.js test/escape.txt # make sure pkgs are installed
