language: node_js
node_js:
  - "node"
dist: trusty
addons:
  apt:
    packages:
      - texlive-full
      - ttf-dejavu
before_install:
  - npm install
  - node ./cli/wa2pdf.js test/escape.txt -n -s # make sure pkgs are installed
