language: node_js
node_js:
  - "node"
dist: trusty
addons:
  apt:
    packages:
      - texlive-xetex
      - ttf-dejavu
before_install:
  - node ./cli/wa2pdf.js test/escape.pdf # make sure pkgs are installed
